name: Test
on: 
  push:
    branches: [ main ]

jobs:
  RunE2ETest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm i
      - name: Install browsers 
        run: npx playwright install
      - name: Run tests
        run: npx playwright test
